authors:
  felipe:
    name: Felipe Bastos Nunes
    description: Docente, Pesquisador e Extensionista do IFCE Campus Aracati
    avatar: https://avatars.githubusercontent.com/u/4561453?v=4
    slug: felipe-bastos-nunes
    url: https://felipebastos.pro.br/